config/routes.rb
Rails.application.routes.draw do

  get 'contact' => 'contact#index'
  get 'recipes/random' => 'recipes#random'

  resources :recipes,     only: [:index, :show]
  resources :ingredients, only: [:index]

  namespace :admin do
    root 'admin/recipes#index'
    resources :recipes,     except: [:show]
    resources :ingredients, except: [:show]
  end

  root 'ingredients#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true,
    uniqueness: true,
    format: { with: /\A[a-z][a-z\s]+[a-z]\z/,
    message: "only allows lowercase letters and whitespace" }

  has_many :ingredients_recipes
  has_many :recipes, through: :ingredients_recipes
end

app/models/ingredients_recipe.rb
class IngredientsRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true,
    uniqueness: true
  validates :description, presence: true
  validates :img_url, presence: true
  validates :ingredient_details, presence: true

  has_many :ingredients_recipes
  has_many :ingredients, through: :ingredients_recipes

  scope :random, -> { order ('RANDOM()') }

  def self.sample_recipe
    random.first
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
  http_basic_authenticate_with name: ENV.fetch('ADMIN_USER_NAME', 'admin'), password: ENV.fetch('ADMIN_PASSWORD', '1234')
end

app/controllers/admin/ingredients_controller.rb
class Admin::IngredientsController < Admin::BaseController

  def index
    @ingredients = Ingredient.all.order(:name)
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)

    if @ingredient.save
      redirect_to admin_ingredients_path, notice: "Ingredient saved"
    else
      render 'new'
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])

    if @ingredient.update(ingredient_params)
      redirect_to admin_ingredients_path, notice: "Ingredient uppdated"
    else
      render 'edit'
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])

    @ingredient.destroy
    redirect_to admin_ingredients_path, notice: "Ingredient deleted"
  end

  private
  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/controllers/admin/recipes_controller.rb
class Admin::RecipesController < Admin::BaseController

  def index
    @recipes = Recipe.all.order(:name)
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      params[:ingredient][:ingredient_id].each do |i|
        @recipe.ingredients_recipes.create(ingredient_id: i)
      end
      redirect_to @recipe, notice: "Recipe saved"
    else
      render 'new'
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      @recipe.ingredients.delete_all
      params[:ingredient][:ingredient_id].each do |i|
        @recipe.ingredients_recipes.create(ingredient_id: i)
      end
      redirect_to admin_recipes_path, notice: "Recipe updated"
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to admin_recipes_path, notice: "Recipe deleted"
  end

  private
  def recipe_params
    params.require(:recipe).permit(:name, :ingredient_id, :ingredient_details, :description, :img_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    if ingredient_id = params["ingredient"]
      ingredient_id = ingredient_id.to_i
      @recipes = Ingredient.find(ingredient_id).recipes

      @sample_recipe = Recipe.sample_recipe unless @recipes.present?
    else
      @recipes = Recipe.all
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def random
    @recipe = Recipe.random.first
    render 'show'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/ingredients/_ingredient.html.erb
<tr>
  <td><%= ingredient.name %></td>
  <td><%= link_to 'Edit', [:edit, :admin, ingredient] %></td>
  <td><%= link_to 'Destroy', [:admin, ingredient], method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/ingredients/edit.html.erb
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--4-col">
    <h1 class="container__recipe--name">Edit ingredient</h1>

    <div>
      <% if @ingredient.errors.any? %>
      <ul>
        <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
      <% end %>
    </div>

    <%= form_for [:admin, @ingredient], method: :patch do |i| %>
    <div class="group flex-for-div">
      <%= i.text_field :name , class: "mdl-grid mdl-cell--12-col"%>
    </div>

    <div class="group margin font">
      <button type="submit"
      class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">
      Submit
      </button>
    </div>
    <% end %>
  </div>
<div class="mdl-layout-spacer"></div>
</div>

app/views/admin/ingredients/index.html.erb
<div class="mdl-grid admin_ingredients--center">
  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--12-col">
    <h1 class="container__recipe--name" style="text-align: center">Ingredients</h1>
    <button class="mdl-button mdl-js-button mdl-button--fab ingredients">
      <i class="material-icons"><%= link_to 'add new', [:new, :admin, :ingredient] %></i>
    </button>
  </div>
</div>

<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--12-col center">
    <table class="table ingredients">
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="2">Options</th>
        </tr>
      </thead>
      <tbody>
        <% @ingredients.each do |ingredient| %>
        <%= render partial: "ingredient", locals: { ingredient: ingredient } %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/ingredients/new.html.erb
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
    <div class="mdl-cell mdl-cell--4-col">
      <h1 class="container__recipe--name"> New ingredient</h1>

      <div>
        <% if @ingredient.errors.any? %>
        <ul>
          <% @ingredient.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
        <% end %>
      </div>

      <%= form_for [:admin, @ingredient] do |i| %>
      <div class="group flex-for-div ">
        <%= i.text_field :name , class: "mdl-grid mdl-cell--12-col"%>
      </div>

      <div class="group margin font">
        <button type="submit"
          class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">
          Submit
        </button>
       </div>
      <% end %>
  </div>
<div class="mdl-layout-spacer"></div>
</div>

app/views/admin/recipes/edit.html.erb
<div class="custom-container">
  <h3 class="container__recipe--name">Edit recipe</h3>
  <div>
    <% if @recipe.errors.any? %>
    <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>
  </div>
  <%= form_for [:admin, @recipe], method: :patch,
  html: {class: "row"} do |recipe| %>
  <div class="flex-for-div">
    <%= recipe.label :name, class:"middle-text" %>
    <%= recipe.text_area :name , class: "mdl-grid mdl-cell--12-col"%>
  </div>
  <div class="group flex-for-div ">
    <%= recipe.label :img_url, class:"middle-text" %>
    <%= recipe.text_area :img_url, class: "mdl-grid mdl-cell--12-col"%>
  </div>
  <div class="group flex-for-div ">
    <%= recipe.label :ingredient_details, class:"middle-text" %>
    <%= recipe.text_area :ingredient_details, class:"textarea-size mdl-grid mdl-cell--12-col"%>
  </div>
  <div class="group flex-for-div ">
    <%= recipe.label :description, class:"middle-text" %>
    <%= recipe.text_area :description, class:"textarea-size mdl-grid mdl-cell--12-col" %>
  </div>
  <div class="group flex-for-div">
    <%= collection_select(:ingredient, :ingredient_id, Ingredient.all.order(:name), :id, :name,
    {selected: @recipe.ingredients.map(&:id)} ,{:multiple => true, class:"js-selectpicker"}) %>
  </div>
  <div class="group margin">
    <button type="submit"
    class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect"
    >Edit</button>
  </div>
  <% end %>

  <%= link_to 'Back', admin_recipes_path %>
</div>

app/views/admin/recipes/index.html.erb
<div class="mdl-grid admin_ingredients--center">
  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--12-col">
    <h1 class="container__recipe--name" style="text-align: center">Recipes</h1>
    <button class="mdl-button mdl-js-button mdl-button--fab ingredients">
      <i class="material-icons"><%= link_to 'add new', [:new, :admin, :recipe] %></i>
    </button>
  </div>
</div>

<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--12-col center">
    <table class="table ingredients">
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="2">Options</th>
        </tr>
      </thead>
      <tbody>
        <% @recipes.each do |recipe| %>
        <tr>
          <td><%= recipe.name %></td>
          <td><%= link_to 'Edit', [:edit, :admin, recipe] %></td>
          <td><%= link_to 'Destroy', [:admin, recipe], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/recipes/new.html.erb
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--6-col">
    <h1 class="container__recipe--name"> New recipe</h1>

    <div>
      <% if @recipe.errors.any? %>
      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
      <% end %>
    </div>

    <%= form_for [:admin, @recipe], method: :post do |recipe| %>
    <div class="flex-for-div">
      <%= recipe.label :name, class:"middle-text" %>
      <%= recipe.text_area :name , class: "mdl-grid mdl-cell--12-col" %>
    </div>
    <div class="group flex-for-div">
      <%= recipe.label :img_url, class:"middle-text" %>
      <%= recipe.text_area :img_url, class: "mdl-grid mdl-cell--12-col"%>
    </div>
    <div class="group flex-for-div ">
      <%= recipe.label :ingredient_details, class:"middle-text" %>
      <%= recipe.text_area :ingredient_details, class:"textarea-size mdl-grid mdl-cell--12-col"%>
    </div>
    <div class="group flex-for-div ">
      <%= recipe.label :description, class:"middle-text" %>
      <%= recipe.text_area :description, class:"textarea-size mdl-grid mdl-cell--12-col" %>
    </div>
    <div class="group flex-for-div">
      <%= collection_select(:ingredient, :ingredient_id, Ingredient.all.order(:name), :id, :name, {} ,
      {:multiple => true, class:"js-selectpicker "}) %>
    </div>

    <div class="group margin">
      <button type="submit"
      class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">
      Submit
      </button>
    </div>
    <% end %>
  </div>
<div class="mdl-layout-spacer"></div>
</div>

app/views/contact/index.html.erb
<div  class="mdl-grid ingrediets-cover lunch-gap--none grid--center">
  <div class="mdl-cell mdl-cell--6-col">
    <h1 class="ingredients-question">Thank you for the visit!</h1>
    <%= image_tag "logo/sygnet.png", class: "fridge-image" %>
    <h4>Any feedback? Drop us a line on:</h4>
    <a href="mailto:luncher@luncher.com" target="_top" class="link">contact@luncher.com</a>
  </div>
</div>

app/views/ingredients/index.html.erb
<div class="mdl-grid lunch-cover lunch-gap--none">
  <div class="mdl-cell mdl-cell--6-col lunch-main-left">
    <h1 class="lunch-main-left__slogan--main">Wanna have</h1>
    <h1 class="advent-pro-font lunch-main-left__slogan--sec">LUNCH?</h1>
  </div>

  <div class="mdl-cell mdl-cell--6-col lunch-main-right">
    <a href="#section2" class="scroll"><button class="lunch-main__button advent-pro-font">YES!</button></a>
  </div>
</div>

<div id="section2" class="mdl-grid ingrediets-cover lunch-gap--none grid--center">
  <div class="mdl-cell mdl-cell--6-col ingredients-cover--center">
    <h1 class="ingredients-question">What do you have in your fridge?</h1>
    <%= image_tag "fridge.png", class: "fridge-image" %>

    <%= form_tag(recipes_path, method: "get", class: "form mdl-grid grid--center") do %>
      <%= select_tag "ingredient", options_from_collection_for_select(@ingredients, "id", "name"),
        class: "mdl-cell--12-col select-landing"%>
      <%= button_tag("GO!", class: "ingredients-go__button advent-pro-font mdl-cell--12-col") %>
    <% end %>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Luncher</title>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <div class="mdl-layout mdl-js-layout">
      <header class="mdl-layout__header lunch-header">
        <div class="mdl-layout__header-row lunch-header-row">
          <%= link_to (image_tag "logo/logo2.png", class: "lunch-header-logo"), root_path  %>
        </div>
      </header>

      <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">ADMIN</span>
          <nav class="mdl-navigation">
            <h6>Main:</h6>
              <%= link_to "Home", root_path, class: "mdl-navigation__link"%>
            <hr />
            <h6>Ingredients:</h6>
              <%= link_to "Add",  new_admin_ingredient_path, class: "mdl-navigation__link"%>
              <%= link_to "List", admin_ingredients_path,     class: "mdl-navigation__link"%>
            <hr />
            <h6>Recipes:</h6>
              <%= link_to "Add",  new_admin_recipe_path, class: "mdl-navigation__link"%>
              <%= link_to "List", admin_recipes_path, class: "mdl-navigation__link"%>
            <hr />
          </nav>
      </div>
      <main class="mdl-layout__content">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Luncher</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <link rel="icon" sizes="16x16" href="/assets/logo/favicon.ico">
  </head>

  <body>
    <div class="mdl-layout mdl-js-layout">
      <header class="mdl-layout__header lunch-header">
        <div class="mdl-layout__header-row lunch-header-row">
          <%= link_to (image_tag "logo/logo2.png", class: "lunch-header-logo"), root_path  %>
        </div>
      </header>
      <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">LUNCHER</span>
        <nav class="mdl-navigation advent-pro-fon">
          <%= link_to "Home", root_path, class: "mdl-navigation__link"%>
          <%= link_to "Recipes", recipes_path, class: "mdl-navigation__link"%>
          <%= link_to "Random!", recipes_random_path, class: "mdl-navigation__link"%>
          <%= link_to "Contact", contact_path, class: "mdl-navigation__link"%>
          <%= link_to "Admin", admin_recipes_path, class: "mdl-navigation__link" %>       
        </nav>
      </div>
      <main class="mdl-layout__content">
        <%= yield %>
      </main>
    </div>
  </body>

</html>

app/views/recipes/index.html.erb
<% unless @recipes.present? %>
  <h1 class="search_results__title">Sorry, you have to cook something else...</h1>
  <div class="mdl-grid container__recipes">
    <div class="mdl-cell mdl-cell--4-col list_item">
      <div class="demo-card-square mdl-card mdl-shadow--2dp">
        <%= link_to(image_tag(@sample_recipe.img_url, class: "image"), @sample_recipe) %>
          <div class="mdl-card__title mdl-card--expand">
            <h2 class="mdl-card__title-text"><%= @sample_recipe.name.capitalize %></h2>
          </div>

          <div class="mdl-card__supporting-text">
            <%= truncate(@sample_recipe.description, length: 80) %>
          </div>

        <div class="mdl-card__actions mdl-card--border">
          <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
            <%= link_to "See full recipe", @sample_recipe, class: "recipe__link" %>
          </a>
        </div>
      </div>
    </div>
  </div>

  <% else %>
    <h1 class="search_results__title">Your search results:</h1>
    <div class="mdl-grid container__recipes">
    <% @recipes.each do |r| %>
      <div class="mdl-cell mdl-cell--4-col list_item">
        <div class="demo-card-square mdl-card mdl-shadow--2dp">
          <%= link_to(image_tag(r.img_url, class: "image"), r) %>
            <div class="mdl-card__title mdl-card--expand">
              <h2 class="mdl-card__title-text"><%= r.name.capitalize %></h2>
            </div>

            <div class="mdl-card__supporting-text">
              <%= truncate(r.description, length: 80) %>
            </div>

          <div class="mdl-card__actions mdl-card--border">
            <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
              <%= link_to "See full recipe", r, class: "recipe__link" %>
            </a>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="container__recipe mdl-grid">
  <div class="container__recipe--description dl-cell mdl-cell--5-col">
    <h1 class="container__recipe--name"><%= @recipe.name.capitalize %> </h1>

    <div class="container__recipe--summary">
      <ul>
        <li>Time: 30 min</li>
        <li>For: 2 people</li>
        <li>Cost: cheap</li>
      </ul>
    </div>

    <div class="container__recipe--ingredients_list"><b>Ingredients:</b><br>
      <%= simple_format(@recipe.ingredient_details) %>
    </div>

    <div class="container__recipe--preparation">
      <%= simple_format(@recipe.description) %>
    </div>
  </div>
  <div class="dl-cell mdl-cell--1-col"></div>
  <div class="container__recipe--image mdl-cell mdl-cell--6-col">
    <%= image_tag(@recipe.img_url) %>
  </div>
</div>